import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class Appointment {
  const Appointment({required this.id,required this.service,required this.duration,required this.price,required this.barber,required this.dateIso,required this.time,required this.createdAtIso,this.serviceId,this.barberId,this.durationMinutes,this.status='scheduled',this.cancelledBy,this.cancelledAtIso,this.completedAtIso,this.completionSource,this.clientName,this.clientEmail,this.clientPhone});
  final String id,service,duration,price,barber,dateIso,time,createdAtIso; final String? serviceId,barberId; final int? durationMinutes; final String status; final String? cancelledBy,cancelledAtIso,completedAtIso,completionSource,clientName,clientEmail,clientPhone;
  DateTime get date=>DateTime.parse(dateIso); bool get isCancelled=>status=='cancelled'; bool get isCompleted=>status=='completed'; bool get isOpen=>status=='scheduled'||status=='confirmed';
  Appointment copyWith({String? status,String? cancelledBy,String? cancelledAtIso,String? completedAtIso,String? completionSource})=>Appointment(id:id,service:service,duration:duration,price:price,barber:barber,dateIso:dateIso,time:time,createdAtIso:createdAtIso,status:status??this.status,cancelledBy:cancelledBy??this.cancelledBy,cancelledAtIso:cancelledAtIso??this.cancelledAtIso,completedAtIso:completedAtIso??this.completedAtIso,completionSource:completionSource??this.completionSource,clientName:clientName,clientEmail:clientEmail,clientPhone:clientPhone,serviceId:serviceId,barberId:barberId,durationMinutes:durationMinutes);
  Map<String,dynamic> toJson()=>{'id':id,'service':service,'duration':duration,'price':price,'barber':barber,'dateIso':dateIso,'time':time,'createdAtIso':createdAtIso,'status':status,'cancelledBy':cancelledBy,'cancelledAtIso':cancelledAtIso,'completedAtIso':completedAtIso,'completionSource':completionSource,'clientName':clientName,'clientEmail':clientEmail,'clientPhone':clientPhone,'serviceId':serviceId,'barberId':barberId,'durationMinutes':durationMinutes};
  factory Appointment.fromJson(Map<String,dynamic> j)=>Appointment(id:j['id'],service:j['service'],duration:j['duration'],price:j['price'],barber:j['barber'],dateIso:j['dateIso'],time:j['time'],createdAtIso:j['createdAtIso'],status:j['status']?.toString()??'scheduled',cancelledBy:j['cancelledBy']?.toString(),cancelledAtIso:j['cancelledAtIso']?.toString(),completedAtIso:j['completedAtIso']?.toString(),completionSource:j['completionSource']?.toString(),clientName:j['clientName']?.toString(),clientEmail:j['clientEmail']?.toString(),clientPhone:j['clientPhone']?.toString(),serviceId:j['serviceId']?.toString(),barberId:j['barberId']?.toString(),durationMinutes:(j['durationMinutes'] as num?)?.toInt());
  Map<String,dynamic> toCloudJson(String clientId){final shop=AppointmentStore.shopId;if(shop==null)throw StateError('Usuário sem estabelecimento selecionado.');final p=time.split(':');final local=DateTime(DateTime.parse(dateIso).year,DateTime.parse(dateIso).month,DateTime.parse(dateIso).day,int.parse(p[0]),int.parse(p[1]));return {'id':id,'barbershop_id':shop,'client_id':clientId,'service_id':serviceId,'barber_id':barberId,'service':service,'duration':duration,'duration_minutes':durationMinutes,'price':price,'barber':barber,'date_iso':dateIso,'time':time,'starts_at':local.toUtc().toIso8601String(),'created_at_iso':createdAtIso,'status':'scheduled'};}
  factory Appointment.fromCloudJson(Map<String,dynamic> j)=>Appointment(id:j['id'].toString(),service:j['service']?.toString()??'',duration:j['duration']?.toString()??'',price:j['price']?.toString()??'',barber:j['barber']?.toString()??'',dateIso:j['date_iso']?.toString()??'',time:j['time']?.toString()??'',createdAtIso:j['created_at_iso']?.toString()??'',status:j['status']?.toString()??'scheduled',cancelledBy:j['cancelled_by']?.toString(),cancelledAtIso:j['cancelled_at']?.toString(),completedAtIso:j['completed_at']?.toString(),completionSource:j['completion_source']?.toString(),clientName:j['client_name']?.toString(),clientEmail:j['client_email']?.toString(),clientPhone:j['client_phone']?.toString());
}
class AppointmentConflictException implements Exception{const AppointmentConflictException();}
class AppointmentStore{
 AppointmentStore._(); static const _key='appointments_v1',_clientShopKey='client_shop_id_v2'; static const _supabaseUrl=String.fromEnvironment('SUPABASE_URL',defaultValue:'https://drvaacngbtnjxdeakgnn.supabase.co'),_supabasePublishableKey=String.fromEnvironment('SUPABASE_PUBLISHABLE_KEY',defaultValue:'sb_publishable_FAPJ5-5m7nnvXP18vw85yQ_QuVAjum8'); static bool _cloudReady=false; static String? _cloudError,_shopId,_shopName,_memberRole;
 static bool get cloudEnabled=>_cloudReady; static String? get cloudError=>_cloudError; static String? get shopId=>_shopId; static String? get shopName=>_shopName; static String? get memberRole=>_memberRole; static bool _platformAdmin=false; static bool get isEstablishmentAdmin=>_memberRole=='owner'||_memberRole=='admin'||_memberRole=='manager'; static bool get isPlatformAdmin=>_platformAdmin; static bool get isAdmin=>isEstablishmentAdmin; static bool get isClient=>signedIn&&!isEstablishmentAdmin&&!isPlatformAdmin; static SupabaseClient get client=>Supabase.instance.client; static User? get currentUser=>client.auth.currentUser; static bool get signedIn=>currentUser!=null&&currentUser!.isAnonymous!=true; static bool get hasShop=>_shopId!=null; static String _clientShopKeyFor(User user)=>'${_clientShopKey}_${user.id}';
 static Future<void> initializeCloud()async{_cloudReady=false;_cloudError=null;_shopId=null;_shopName=null;_memberRole=null;if(_supabaseUrl.isEmpty||_supabasePublishableKey.isEmpty){_cloudError='Configuração do Supabase ausente no APK.';return;}try{await Supabase.initialize(url:_supabaseUrl,publishableKey:_supabasePublishableKey);if(client.auth.currentUser?.isAnonymous==true)await client.auth.signOut();if(client.auth.currentUser!=null)await refreshMembership();else _cloudError='Entre com sua conta.';}catch(e,s){_cloudReady=false;_cloudError=e.toString();debugPrint('[Supabase] Falha ao inicializar: $e');debugPrintStack(stackTrace:s);}}
 static Future<void> signIn(String email,String password)async{_cloudReady=false;_cloudError=null;await client.auth.signInWithPassword(email:email.trim(),password:password);await refreshMembership();}
 static Future<bool> signUp(String email,String password)async{_cloudReady=false;_cloudError=null;final r=await client.auth.signUp(email:email.trim(),password:password);if(r.session!=null){await refreshMembership();return true;}_cloudError='Confirme seu e-mail e depois faça login.';return false;}
 static Future<void> signOut()async{await client.auth.signOut();_cloudReady=false;_shopId=null;_shopName=null;_memberRole=null;_platformAdmin=false;_cloudError='Entre com sua conta.';}
 static Future<void> refreshMembership()async{final user=client.auth.currentUser;_cloudReady=false;_shopId=null;_shopName=null;_memberRole=null;_platformAdmin=false;if(user==null||user.isAnonymous==true){_cloudError='Login permanente necessário.';return;}try{_platformAdmin=(await client.rpc('is_platform_admin'))==true;}catch(_){_platformAdmin=false;}final rows=await client.from('barbershop_members').select('barbershop_id,role').eq('user_id',user.id).limit(1);final list=rows as List<dynamic>;if(list.isNotEmpty){final row=list.first as Map<String,dynamic>;_shopId=row['barbershop_id'] as String;_memberRole=row['role'] as String?;final shops=await client.from('barbershops').select('name').eq('id',_shopId!).limit(1);final shopList=shops as List<dynamic>;if(shopList.isNotEmpty)_shopName=(shopList.first as Map<String,dynamic>)['name']?.toString();_cloudReady=true;_cloudError=null;return;}final metadata=user.userMetadata??const <String,dynamic>{};if(metadata['account_type']=='barbershop_admin'){_cloudError='Conta do estabelecimento ainda não configurada.';return;}final prefs=await SharedPreferences.getInstance();final saved=prefs.getString(_clientShopKeyFor(user));if(saved!=null&&saved.isNotEmpty){final shops=await client.from('barbershops').select('id,name').eq('id',saved).eq('active',true).limit(1);final shopList=shops as List<dynamic>;if(shopList.isNotEmpty){final shop=shopList.first as Map<String,dynamic>;_shopId=shop['id']?.toString();_shopName=shop['name']?.toString();_memberRole=null;_cloudReady=true;_cloudError=null;return;}await prefs.remove(_clientShopKeyFor(user));}_cloudError='Escolha um estabelecimento para continuar.';}
 static Future<List<Map<String,dynamic>>> listActiveBarbershops()async{if(!signedIn)throw StateError('Faça login primeiro.');final rows=await client.from('barbershops').select('id,name,slug').eq('active',true).order('name');return(rows as List<dynamic>).cast<Map<String,dynamic>>();}
 static Future<void> selectClientShop(String id)async{final user=currentUser;if(user==null||user.isAnonymous==true)throw StateError('Faça login primeiro.');final rows=await client.from('barbershops').select('id,name').eq('id',id).eq('active',true).limit(1);final list=rows as List<dynamic>;if(list.isEmpty)throw StateError('Estabelecimento indisponível.');final shop=list.first as Map<String,dynamic>;final prefs=await SharedPreferences.getInstance();await prefs.setString(_clientShopKeyFor(user),id);_shopId=id;_shopName=shop['name']?.toString();_memberRole=null;_cloudReady=true;_cloudError=null;}
 static Future<void> clearClientShop()async{final user=currentUser;if(user!=null){final prefs=await SharedPreferences.getInstance();await prefs.remove(_clientShopKeyFor(user));}_shopId=null;_shopName=null;_cloudReady=false;_cloudError='Escolha um estabelecimento para continuar.';}
 static Future<void> claimOwnerAccess(String inviteCode)async{if(!signedIn)throw StateError('Faça login primeiro.');await client.rpc('claim_barbershop_owner',params:{'invite_code':inviteCode.trim()});await refreshMembership();}
 static Future<List<Appointment>> load()async{if(cloudEnabled){try{final r=await _loadRemote();await _save(r);return r;}catch(e,s){_cloudError=e.toString();debugPrint('[Supabase] Falha ao carregar agenda: $e');debugPrintStack(stackTrace:s);}}return _loadLocal();}
 static Future<void> add(Appointment a)async{if(!cloudEnabled)throw StateError(_cloudError??'Agenda na nuvem indisponível.');try{await _addRemote(a);_cloudError=null;}catch(e,s){_cloudError=e.toString();debugPrint('[Supabase] Falha ao inserir agendamento: $e');debugPrintStack(stackTrace:s);rethrow;}final items=await _loadLocal();items.removeWhere((x)=>x.id==a.id);items.add(a);items.sort(_compareAppointments);await _save(items);}
 static Future<void> remove(String id)async{if(!cloudEnabled)throw StateError(_cloudError??'Agenda na nuvem indisponível.');final cancelledBy=isAdmin?'admin':'client',cancelledAtIso=DateTime.now().toUtc().toIso8601String();try{await _removeRemote(id,cancelledBy,cancelledAtIso);_cloudError=null;}catch(e,s){_cloudError=e.toString();debugPrint('[Supabase] Falha ao cancelar agendamento: $e');debugPrintStack(stackTrace:s);rethrow;}final items=await _loadLocal();final index=items.indexWhere((x)=>x.id==id);if(index>=0){items[index]=items[index].copyWith(status:'cancelled',cancelledBy:cancelledBy,cancelledAtIso:cancelledAtIso);await _save(items);}}
 static Future<void> complete(String id)async{if(!cloudEnabled)throw StateError(_cloudError??'Agenda na nuvem indisponível.');if(!isAdmin)throw StateError('Apenas o estabelecimento pode concluir atendimentos.');try{final row=await client.rpc('complete_appointment',params:{'p_appointment_id':id});_cloudError=null;final items=await _loadLocal();final index=items.indexWhere((x)=>x.id==id);if(index>=0){final m=row is Map<String,dynamic>?row:(row is List&&row.isNotEmpty?Map<String,dynamic>.from(row.first as Map):<String,dynamic>{});items[index]=items[index].copyWith(status:'completed',completedAtIso:m['completed_at']?.toString()??DateTime.now().toUtc().toIso8601String(),completionSource:m['completion_source']?.toString()??'manual');await _save(items);}}catch(e,s){_cloudError=e.toString();debugPrint('[Supabase] Falha ao concluir agendamento: $e');debugPrintStack(stackTrace:s);rethrow;}}
 static Future<List<Appointment>> _loadLocal()async{final p=await SharedPreferences.getInstance();final raw=p.getString(_key);if(raw==null||raw.isEmpty)return[];try{final d=jsonDecode(raw) as List<dynamic>;final items=d.map((x)=>Appointment.fromJson(x as Map<String,dynamic>)).toList();items.sort(_compareAppointments);return items;}catch(_){return[];}}
 static Future<List<Appointment>> _loadRemote()async{final user=client.auth.currentUser,shop=shopId;if(user==null)throw StateError('Sessão Supabase não autenticada.');if(shop==null)throw StateError('Estabelecimento não selecionado.');if(isAdmin){final rows=await client.rpc('admin_appointments_with_client_identity');final items=(rows as List<dynamic>).map((x)=>Appointment.fromCloudJson(x as Map<String,dynamic>)).toList();items.sort(_compareAppointments);return items;}var q=client.from('appointments').select('id,service,duration,price,barber,date_iso,time,created_at_iso,status,cancelled_by,cancelled_at,completed_at,completion_source,client_phone').eq('barbershop_id',shop).eq('client_id',user.id);final rows=await q.order('date_iso').order('time');final items=(rows as List<dynamic>).map((x)=>Appointment.fromCloudJson(x as Map<String,dynamic>)).toList();items.sort(_compareAppointments);return items;}
 static Future<void> _addRemote(Appointment a)async{final user=client.auth.currentUser;if(user==null)throw StateError('Sessão Supabase não autenticada.');try{await client.from('appointments').insert(a.toCloudJson(user.id));}on PostgrestException catch(e){if(e.code=='23505')throw const AppointmentConflictException();rethrow;}}
 static Future<void> _removeRemote(String id,String cancelledBy,String cancelledAtIso)async{final shop=shopId,user=client.auth.currentUser;if(user==null)throw StateError('Sessão Supabase não autenticada.');if(shop==null)throw StateError('Estabelecimento não selecionado.');var q=client.from('appointments').update({'status':'cancelled','cancelled_by':cancelledBy,'cancelled_at':cancelledAtIso}).eq('id',id).eq('barbershop_id',shop);if(!isAdmin)q=q.eq('client_id',user.id);await q;}
 static Future<void> _save(List<Appointment> items)async{final p=await SharedPreferences.getInstance();await p.setString(_key,jsonEncode(items.map((x)=>x.toJson()).toList()));}
 static int _compareAppointments(Appointment a,Appointment b){DateTime v(Appointment x){final p=x.time.split(':');return DateTime(x.date.year,x.date.month,x.date.day,int.parse(p[0]),int.parse(p[1]));}return v(a).compareTo(v(b));}
}
