import 'dart:async';
import 'package:flutter/material.dart';
import 'appointment_store.dart';

class AuthGate extends StatefulWidget { const AuthGate({super.key,required this.child}); final Widget child; @override State<AuthGate> createState()=>_AuthGateState(); }
class _AuthGateState extends State<AuthGate>{
 bool _loading=true,_register=false,_registerAsAdmin=false; String? _message;
 final _email=TextEditingController(),_password=TextEditingController(),_fullName=TextEditingController(),_barbershopName=TextEditingController(); StreamSubscription? _authSubscription;
 @override void initState(){super.initState();_authSubscription=AppointmentStore.client.auth.onAuthStateChange.listen((_){if(mounted)_refresh();});_refresh();}
 @override void dispose(){_authSubscription?.cancel();_email.dispose();_password.dispose();_fullName.dispose();_barbershopName.dispose();super.dispose();}
 Future<void> _refresh()async{if(!mounted)return;setState(()=>_loading=true);try{if(AppointmentStore.signedIn){await AppointmentStore.refreshMembership();if(!AppointmentStore.hasShop)await _provisionAdminIfNeeded();}}catch(e){_message=_friendlyError(e);}if(mounted)setState(()=>_loading=false);}
 Future<void> _provisionAdminIfNeeded()async{final user=AppointmentStore.currentUser;if(user==null||AppointmentStore.hasShop)return;final metadata=user.userMetadata??const <String,dynamic>{};if(metadata['account_type']!='barbershop_admin')return;final shopName=(metadata['barbershop_name'] as String?)?.trim()??'';if(shopName.length<2)throw StateError('Nome do estabelecimento ausente no cadastro.');await AppointmentStore.client.rpc('bootstrap_barbershop_admin',params:{'p_barbershop_name':shopName});await AppointmentStore.refreshMembership();}
 Future<void> _submitAuth()async{final email=_email.text.trim(),password=_password.text;if(email.isEmpty||password.length<6){setState(()=>_message='Informe um e-mail valido e senha com pelo menos 6 caracteres.');return;}if(_register&&_fullName.text.trim().length<2){setState(()=>_message='Informe seu nome.');return;}if(_register&&_registerAsAdmin&&_barbershopName.text.trim().length<2){setState(()=>_message='Informe o nome do estabelecimento.');return;}setState((){_loading=true;_message=null;});try{if(_register){final data=<String,dynamic>{'full_name':_fullName.text.trim(),'account_type':_registerAsAdmin?'barbershop_admin':'client'};if(_registerAsAdmin)data['barbershop_name']=_barbershopName.text.trim();final response=await AppointmentStore.client.auth.signUp(email:email,password:password,emailRedirectTo:'com.barbeariaagenda.app://login-callback',data:data);if(response.session!=null)await _refresh();else _message='Conta criada. Enviamos um e-mail de confirmacao. Toque no link para concluir o cadastro.';}else{await AppointmentStore.signIn(email,password);if(!AppointmentStore.hasShop)await _provisionAdminIfNeeded();}}catch(e){_message=_friendlyError(e);}if(mounted)setState(()=>_loading=false);}
 String _friendlyError(Object error){final t=error.toString();if(t.contains('Invalid login credentials'))return'E-mail ou senha incorretos.';if(t.contains('Email not confirmed'))return'Confirme seu e-mail antes de entrar.';if(t.contains('already registered'))return'Este e-mail ja possui cadastro.';if(t.contains('Email confirmation required'))return'Confirme seu e-mail antes de continuar.';if(t.contains('Authentication required'))return'Sessao expirada. Entre novamente.';return t;}
 @override Widget build(BuildContext context){if(_loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(!AppointmentStore.signedIn)return _LoginPage(register:_register,registerAsAdmin:_registerAsAdmin,email:_email,password:_password,fullName:_fullName,barbershopName:_barbershopName,message:_message,onSubmit:_submitAuth,onToggle:()=>setState((){_register=!_register;_message=null;}),onAccountTypeChanged:(v)=>setState(()=>_registerAsAdmin=v));if(!AppointmentStore.hasShop){final type=AppointmentStore.currentUser?.userMetadata?['account_type'];if(type=='barbershop_admin')return _ProvisioningPage(email:AppointmentStore.currentUser?.email??'Conta autenticada',message:_message??AppointmentStore.cloudError,onRetry:_refresh,onLogout:_logout);return _ClientShopPage(onSelected:(id)async{setState(()=>_loading=true);try{await AppointmentStore.selectClientShop(id);}catch(e){_message=_friendlyError(e);}if(mounted)setState(()=>_loading=false);},onLogout:_logout);}return widget.child;}
 Future<void> _logout()async{await AppointmentStore.signOut();if(mounted)setState((){});}
}

class _LoginPage extends StatelessWidget{
 const _LoginPage({required this.register,required this.registerAsAdmin,required this.email,required this.password,required this.fullName,required this.barbershopName,required this.message,required this.onSubmit,required this.onToggle,required this.onAccountTypeChanged});
 final bool register,registerAsAdmin;final TextEditingController email,password,fullName,barbershopName;final String? message;final VoidCallback onSubmit,onToggle;final ValueChanged<bool> onAccountTypeChanged;
 @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
 const Icon(Icons.calendar_month_rounded,size:58,color:Color(0xFFD7A84B)),const SizedBox(height:12),const Text('AGENDA HUB',textAlign:TextAlign.center,style:TextStyle(color:Color(0xFFD7A84B),fontSize:13,fontWeight:FontWeight.w900,letterSpacing:2.4)),const SizedBox(height:8),Text(register?'Criar conta':'Entrar no Agenda Hub',textAlign:TextAlign.center,style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:8),
 Text(register?(registerAsAdmin?'Cadastre o responsável. O estabelecimento será criado após confirmar o e-mail.':'Crie sua conta de cliente e escolha onde deseja agendar.'):'Sua agenda, serviços e profissionais em um só lugar.',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white60)),const SizedBox(height:24),
 if(register)...[SegmentedButton<bool>(segments:const [ButtonSegment(value:false,label:Text('CLIENTE'),icon:Icon(Icons.person_outline)),ButtonSegment(value:true,label:Text('RESPONSÁVEL'),icon:Icon(Icons.storefront_outlined))],selected:{registerAsAdmin},onSelectionChanged:(s)=>onAccountTypeChanged(s.first)),const SizedBox(height:18),TextField(controller:fullName,textCapitalization:TextCapitalization.words,decoration:const InputDecoration(labelText:'Seu nome',prefixIcon:Icon(Icons.person_outline_rounded),border:OutlineInputBorder())),const SizedBox(height:14),if(registerAsAdmin)...[TextField(controller:barbershopName,textCapitalization:TextCapitalization.words,decoration:const InputDecoration(labelText:'Nome do estabelecimento',prefixIcon:Icon(Icons.storefront_outlined),border:OutlineInputBorder())),const SizedBox(height:14)]],
 TextField(controller:email,keyboardType:TextInputType.emailAddress,autocorrect:false,decoration:const InputDecoration(labelText:'E-mail',prefixIcon:Icon(Icons.mail_outline_rounded),border:OutlineInputBorder())),const SizedBox(height:14),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Senha',prefixIcon:Icon(Icons.lock_outline_rounded),border:OutlineInputBorder())),if(message!=null)...[const SizedBox(height:14),Text(message!,textAlign:TextAlign.center,style:const TextStyle(color:Colors.amberAccent))],const SizedBox(height:20),FilledButton(onPressed:onSubmit,style:FilledButton.styleFrom(backgroundColor:const Color(0xFFD7A84B),foregroundColor:Colors.black,padding:const EdgeInsets.symmetric(vertical:16)),child:Text(register?'CRIAR CONTA':'ENTRAR',style:const TextStyle(fontWeight:FontWeight.w900))),TextButton(onPressed:onToggle,child:Text(register?'Ja tenho conta':'Criar nova conta'))
 ]))))));
}
class _ClientShopPage extends StatefulWidget{const _ClientShopPage({required this.onSelected,required this.onLogout});final Future<void> Function(String) onSelected;final VoidCallback onLogout;@override State<_ClientShopPage> createState()=>_ClientShopPageState();}
class _ClientShopPageState extends State<_ClientShopPage>{late Future<List<Map<String,dynamic>>> _future;@override void initState(){super.initState();_future=AppointmentStore.listActiveBarbershops();}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Escolha o estabelecimento'),actions:[IconButton(onPressed:widget.onLogout,icon:const Icon(Icons.logout))]),body:FutureBuilder<List<Map<String,dynamic>>>(future:_future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Padding(padding:const EdgeInsets.all(24),child:Text('Não foi possível carregar os estabelecimentos.\n${s.error}',textAlign:TextAlign.center)));final shops=s.data??[];if(shops.isEmpty)return const Center(child:Text('Nenhum estabelecimento ativo encontrado.'));return ListView.separated(padding:const EdgeInsets.all(20),itemCount:shops.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(context,i){final shop=shops[i];return Card(child:ListTile(leading:const Icon(Icons.storefront,color:Color(0xFFD7A84B)),title:Text(shop['name']?.toString()??'Estabelecimento'),subtitle:const Text('Toque para acessar e agendar'),trailing:const Icon(Icons.chevron_right),onTap:()=>widget.onSelected(shop['id'].toString())));});}));}
class _ProvisioningPage extends StatelessWidget{const _ProvisioningPage({required this.email,required this.message,required this.onRetry,required this.onLogout});final String email;final String? message;final VoidCallback onRetry,onLogout;@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.storefront_outlined,size:58,color:Color(0xFFD7A84B)),const SizedBox(height:18),const Text('Configurando seu estabelecimento',textAlign:TextAlign.center,style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(email,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white60)),const SizedBox(height:24),Text(message??'Aguarde enquanto concluímos seu cadastro.',textAlign:TextAlign.center,style:const TextStyle(color:Colors.amberAccent)),const SizedBox(height:20),FilledButton(onPressed:onRetry,child:const Text('TENTAR NOVAMENTE')),TextButton(onPressed:onLogout,child:const Text('Sair desta conta'))]))))));}
