import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';
import 'appointment_store.dart';
import 'barber_store.dart';
import 'service_store.dart';
class BookingPage extends StatefulWidget{const BookingPage({super.key});@override State<BookingPage> createState()=>_S();}
class _S extends State<BookingPage>{static const g=Color(0xFFD7A84B),c=Color(0xFF1D1D1D);static const u=Uuid();List<ServiceRecord>s=[];List<BarberRecord>b=[];List<String>times=[];Set<String>busy={};int si=0,bi=0,req=0;DateTime d=DateTime.now();String? time;bool load=true,avail=false,save=false;@override void initState(){super.initState();loadAll();}String iso()=>DateTime(d.year,d.month,d.day).toIso8601String();String fd(DateTime x)=>'${x.day.toString().padLeft(2,'0')}/${x.month.toString().padLeft(2,'0')}/${x.year}';String hm(int m)=>'${(m~/60).toString().padLeft(2,'0')}:${(m%60).toString().padLeft(2,'0')}';void msg(String x)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));
Future<void>loadAll()async{setState(()=>load=true);try{final r=await Future.wait([ServiceStore.loadActive(),BarberStore.loadActive()]);if(!mounted)return;setState((){s=r[0] as List<ServiceRecord>;b=r[1] as List<BarberRecord>;load=false;});if(b.isNotEmpty)await refresh();}catch(e){if(mounted){setState(()=>load=false);msg('Não foi possível carregar o catálogo.');}}}
Future<void>refresh()async{if(b.isEmpty)return;final n=++req;setState(()=>avail=true);try{final shop=AppointmentStore.shopId!,p=b[bi];dynamic q=AppointmentStore.client.from(p.usesCustomSchedule?'barber_custom_hours':'barbershop_business_hours').select('enabled,start_minutes,end_minutes,break_enabled,break_start_minutes,break_end_minutes').eq('barbershop_id',shop).eq('weekday',d.weekday);if(p.usesCustomSchedule)q=q.eq('barber_id',p.id);final h=await q.maybeSingle();final a=<String>[];if(h!=null&&h['enabled']==true){final st=h['start_minutes'] as int?,en=h['end_minutes'] as int?,bs=h['break_start_minutes'] as int?,be=h['break_end_minutes'] as int?,br=h['break_enabled']==true;if(st!=null&&en!=null)for(int m=st;m<en;m+=60){if(!(br&&bs!=null&&be!=null&&m>=bs&&m<be))a.add(hm(m));}}final rows=await AppointmentStore.client.from('appointments').select('time').eq('barbershop_id',shop).eq('barber',p.name).eq('date_iso',iso()).eq('status','scheduled');final z=(rows as List).map((x)=>(x as Map)['time']?.toString()).whereType<String>().toSet();if(!mounted||n!=req)return;setState((){times=a;busy=z;if(time!=null&&!a.contains(time))time=null;avail=false;});}catch(e){if(mounted&&n==req){setState((){times=[];avail=false;});msg('Não foi possível carregar os horários.');}}}
Future<void>pick()async{final n=DateTime.now(),x=await showDatePicker(context:context,initialDate:d.isBefore(n)?n:d,firstDate:DateTime(n.year,n.month,n.day),lastDate:n.add(const Duration(days:90)));if(x!=null){setState((){d=x;time=null;});await refresh();}}
Future<void>confirm()async{if(time==null){msg('Escolha um horário.');return;}setState(()=>save=true);final sv=s[si],p=b[bi];try{await AppointmentStore.add(Appointment(id:u.v4(),service:sv.name,duration:sv.formattedDuration,price:sv.formattedPrice,barber:p.name,dateIso:iso(),time:time!,createdAtIso:DateTime.now().toIso8601String()));if(mounted){msg('Agendamento confirmado.');Navigator.pop(context,true);}}on AppointmentConflictException{await refresh();if(mounted)msg('Horário já reservado.');}catch(e){if(mounted)msg('Não foi possível salvar o agendamento.');}finally{if(mounted)setState(()=>save=false);}}
Widget title(String n,String x)=>Row(children:[CircleAvatar(radius:14,backgroundColor:g,child:Text(n,style:const TextStyle(color:Colors.black,fontWeight:FontWeight.bold))),const SizedBox(width:10),Text(x,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900))]);
@override Widget build(BuildContext context){final blocked=load||s.isEmpty||b.isEmpty;return Scaffold(appBar:AppBar(title:const Text('Agendar horário',style:TextStyle(fontWeight:FontWeight.w800))),body:RefreshIndicator(onRefresh:loadAll,child:ListView(padding:const EdgeInsets.all(20),children:[title('1','Serviço'),const SizedBox(height:10),if(load)const LinearProgressIndicator() else ...List.generate(s.length,(i)=>Card(color:si==i?const Color(0xFF292216):c,child:ListTile(onTap:()=>setState(()=>si=i),leading:Icon(si==i?Icons.radio_button_checked:Icons.radio_button_off,color:g),title:Text(s[i].name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(s[i].formattedDuration),trailing:Text(s[i].formattedPrice,style:const TextStyle(color:g,fontWeight:FontWeight.bold))))),const SizedBox(height:20),title('2','Profissional'),const SizedBox(height:10),Wrap(spacing:8,children:List.generate(b.length,(i)=>ChoiceChip(selected:bi==i,label:Text(b[i].name),selectedColor:g,onSelected:(_){setState((){bi=i;time=null;});refresh();}))),const SizedBox(height:20),title('3','Data'),const SizedBox(height:10),Card(color:c,child:ListTile(onTap:blocked?null:pick,leading:const Icon(Icons.calendar_month,color:g),title:Text(fd(d),style:const TextStyle(fontWeight:FontWeight.bold)),trailing:const Icon(Icons.chevron_right))),const SizedBox(height:20),Row(children:[Expanded(child:title('4','Horário')),if(avail)const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2))]),const SizedBox(height:10),if(!avail&&times.isEmpty)const Text('Profissional não trabalha nesta data.',style:TextStyle(color:Colors.white60)) else Wrap(spacing:10,runSpacing:10,children:times.map((x){final o=busy.contains(x);return ChoiceChip(selected:time==x,label:Text(o?'$x • Reservado':x),selectedColor:g,onSelected:o||avail?null:(_)=>setState(()=>time=x));}).toList()),const SizedBox(height:28),if(s.isNotEmpty&&b.isNotEmpty)Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xFF242015),borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Resumo',style:TextStyle(color:g,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${s[si].name} • ${s[si].formattedPrice} • ${s[si].formattedDuration}',style:const TextStyle(fontWeight:FontWeight.bold)),Text('${b[bi].name} • ${fd(d)}${time==null?'':' • $time'}',style:const TextStyle(color:Colors.white60))])),const SizedBox(height:18),FilledButton.icon(onPressed:save||blocked?null:confirm,style:FilledButton.styleFrom(backgroundColor:g,foregroundColor:Colors.black,padding:const EdgeInsets.symmetric(vertical:16)),icon:const Icon(Icons.check),label:Text(save?'SINCRONIZANDO...':'CONFIRMAR AGENDAMENTO',style:const TextStyle(fontWeight:FontWeight.w900)))])));}}
