import 'package:flutter/material.dart';
import 'platform_admin_store.dart';

class PlatformAdminPage extends StatefulWidget{const PlatformAdminPage({super.key});@override State<PlatformAdminPage> createState()=>_PlatformAdminPageState();}
class _PlatformAdminPageState extends State<PlatformAdminPage>{
 static const gold=Color(0xFFD7A84B);bool loading=true;List<Map<String,dynamic>> shops=[],plans=[],audit=[];
 @override void initState(){super.initState();load();}
 Future<void> load()async{setState(()=>loading=true);try{final r=await Future.wait([PlatformAdminStore.loadShops(),PlatformAdminStore.loadPlans(),PlatformAdminStore.loadAudit()]);if(!mounted)return;setState((){shops=r[0];plans=r[1];audit=r[2];loading=false;});}catch(e){if(!mounted)return;setState(()=>loading=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Falha ao carregar administração: #e')));}}
 int? lim(String v)=>v.trim().isEmpty?null:int.tryParse(v.trim());
 String dateOnly(dynamic v){if(v==null)return '—';final d=DateTime.tryParse(v.toString())?.toLocal();if(d==null)return '—';String n(int x)=>x.toString().padLeft(2,'0');return '${n(d.day)}/${n(d.month)}/${d.year}';}
 @override Widget build(BuildContext context)=>DefaultTabController(length:3,child:Scaffold(appBar:AppBar(title:const Text('Administração Agenda Hub',style:TextStyle(fontWeight:FontWeight.w800)),bottom:const TabBar(labelPadding:EdgeInsets.symmetric(horizontal:8),tabs:[Tab(child:FittedBox(fit:BoxFit.scaleDown,child:Text('Estabelecimentos',maxLines:1,softWrap:false))),Tab(text:'Planos'),Tab(text:'Auditoria')])),body:loading?const Center(child:CircularProgressIndicator()):TabBarView(children:[shopsView(),plansView(),auditView()])));
 Widget shopsView()=>RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[summary(),const SizedBox(height:16),...shops.map(shopCard)]));
 Widget summary(){final active=shops.where((s)=>s['active']==true).length;return Row(children:[metric('Estabelecimentos','${shops.length}'),const SizedBox(width:8),metric('Ativos','$active'),const SizedBox(width:8),metric('Planos','${plans.length}')]);}
 Widget metric(String l,String v)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Text(v,style:const TextStyle(color:gold,fontSize:22,fontWeight:FontWeight.w900)),SizedBox(width:double.infinity,child:FittedBox(fit:BoxFit.scaleDown,child:Text(l,maxLines:1,softWrap:false,textAlign:TextAlign.center,style:const TextStyle(fontSize:10,color:Colors.white60))))]))));
 Widget shopCard(Map<String,dynamic>s){final sub=s['subscription'] as Map<String,dynamic>?;return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(s['name']?.toString()??'',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800))),Switch(value:s['active']==true,onChanged:(v)async{await PlatformAdminStore.setShopActive(s['id'].toString(),v);await load();})]),Text('Plano: ${sub?['plan_id']??'—'} • Status: ${sub?['status']??'—'}',style:const TextStyle(color:gold,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text('Vencimento: ${dateOnly(sub?['current_period_end'])}${sub?['status']=='past_due'?' • Tolerância de 3 dias':''}',style:TextStyle(color:sub?['status']=='past_due'?Colors.orangeAccent:Colors.white70,fontWeight:FontWeight.w600)),const SizedBox(height:5),Text('Profissionais ativos: ${s['active_professionals']} • Limite do plano: ${s['effective_max_professionals']??'Ilimitado'}\nAgendamentos: ${s['appointments']}',style:const TextStyle(color:Colors.white70)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:[OutlinedButton.icon(onPressed:()=>editSubscription(s),icon:const Icon(Icons.manage_accounts_rounded),label:const Text('ASSINATURA E LIMITES')),FilledButton.icon(onPressed:()=>registerPix(s),icon:const Icon(Icons.pix),label:const Text('REGISTRAR PIX')),TextButton.icon(onPressed:()=>paymentHistory(s),icon:const Icon(Icons.receipt_long),label:const Text('PAGAMENTOS'))])])));}
 Future<void> editSubscription(Map<String,dynamic>s)async{final sub=(s['subscription'] as Map<String,dynamic>?)??{};String plan=sub['plan_id']?.toString()??'basic',status=sub['status']?.toString()??'trial';final p=TextEditingController(text:sub['custom_max_professionals']?.toString()??''),a=TextEditingController(text:sub['custom_max_monthly_appointments']?.toString()??'');final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:Text(s['name'].toString()),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:plan,decoration:const InputDecoration(labelText:'Plano'),items:plans.map((x)=>DropdownMenuItem(value:x['id'].toString(),child:Text(x['name'].toString()))).toList(),onChanged:(v)=>setD(()=>plan=v!)),DropdownButtonFormField<String>(initialValue:status,decoration:const InputDecoration(labelText:'Status'),items:['trial','active','past_due','cancelled','suspended'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setD(()=>status=v!)),TextField(controller:p,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Limite personalizado de profissionais')),TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Limite personalizado de agendamentos'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar'))])));if(ok==true){await PlatformAdminStore.updateSubscription(s['id'].toString(),planId:plan,status:status,maxProfessionals:lim(p.text),maxAppointments:lim(a.text));await load();}}
 Future<void> registerPix(Map<String,dynamic>s)async{final sub=(s['subscription'] as Map<String,dynamic>?)??{};String plan=sub['plan_id']?.toString()??(plans.isNotEmpty?plans.first['id'].toString():'basic');final value=TextEditingController(),notes=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:const Text('Registrar pagamento Pix'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:plan,decoration:const InputDecoration(labelText:'Plano'),items:plans.where((x)=>x['active']==true).map((x)=>DropdownMenuItem(value:x['id'].toString(),child:Text(x['name'].toString()))).toList(),onChanged:(v)=>setD(()=>plan=v!)),TextField(controller:value,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Valor pago (R$)')),TextField(controller:notes,decoration:const InputDecoration(labelText:'Observação (opcional)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Confirmar pagamento'))])));if(ok!=true)return;final parsed=double.tryParse(value.text.trim().replaceAll(',','.'));if(parsed==null||parsed<=0){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Informe um valor válido.')));return;}try{await PlatformAdminStore.confirmPixPayment(s['id'].toString(),planId:plan,amountCents:(parsed*100).round(),notes:notes.text.trim().isEmpty?null:notes.text.trim());await load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Pagamento confirmado. Assinatura renovada por 30 dias.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Não foi possível registrar o pagamento: $e')));}}
 Future<void> paymentHistory(Map<String,dynamic>s)async{try{final rows=await PlatformAdminStore.loadPayments(s['id'].toString());if(!mounted)return;await showDialog<void>(context:context,builder:(c)=>AlertDialog(title:Text('Pagamentos — ${s['name']}'),content:SizedBox(width:500,child:rows.isEmpty?const Text('Nenhum pagamento registrado.'):ListView(shrinkWrap:true,children:rows.map((x){final cents=(x['amount_cents'] as num?)?.toInt()??0;final amount=(cents/100).toStringAsFixed(2).replaceAll('.',',');return ListTile(contentPadding:EdgeInsets.zero,title:Text('Pix • R\$ $amount'),subtitle:Text('Plano: ${x['plan_id']} • Pago em: ${x['paid_at']}\nVálido até: ${x['period_end']}'));}).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Fechar'))]));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Falha ao carregar pagamentos: $e')));}}
 Widget plansView()=>RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:plans.map(planCard).toList()));
 Widget planCard(Map<String,dynamic>p)=>Card(child:ListTile(title:Text(p['name'].toString(),style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Profissionais: ${p['max_professionals']??'Ilimitado'} • Agendamentos/mês: ${p['max_monthly_appointments']??'Ilimitado'}'),trailing:const Icon(Icons.edit_rounded),onTap:()=>editPlan(p)));
 Future<void> editPlan(Map<String,dynamic>x)async{final p=TextEditingController(text:x['max_professionals']?.toString()??''),a=TextEditingController(text:x['max_monthly_appointments']?.toString()??'');bool active=x['active']==true;final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:Text('Plano ${x['name']}'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:p,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Máx. profissionais')),TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Máx. agendamentos/mês')),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Plano ativo'),value:active,onChanged:(v)=>setD(()=>active=v))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar'))])));if(ok==true){await PlatformAdminStore.updatePlan(x['id'].toString(),maxProfessionals:lim(p.text),maxAppointments:lim(a.text),active:active);await load();}}
 Widget auditView()=>RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:audit.isEmpty?[const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('Nenhuma alteração administrativa registrada.')))] : audit.map((x)=>Card(child:ListTile(title:Text(x['action']?.toString()??''),subtitle:Text('${x['entity_type']} • ${x['entity_id']??''}\n${x['created_at']??''}'),isThreeLine:true))).toList()));
}
